name: Hardhat Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
    
    - name: Run Delta Neutral tests
      env:
        PRIVATE_KEY: ${{ secrets.HARDHAT_PRIVATE_KEY }}
      run: npx hardhat test test/deltaNeutral/deltaNeutralVault_testcases.ts
    
    - name: Run Delta Neutral tests
      env:
        PRIVATE_KEY: ${{ secrets.HARDHAT_PRIVATE_KEY }}
      run: npx hardhat test test/stableUsdc/RockOnyxStableCoinVault_TestCases.ts && npx hardhat test test/stableUsdc/RockOnyxStableCoinVault.ts